### ISSUE TITLE
Error after deploying

### ISSUE THREAD

**Issue by amie33r** [priiiiyo/priiiiyo-mirror-bot#2]
2021-06-04 15:16:47,183 - pmb.helper.config.dynamic - INFO - Using Static Config...

2021-06-04T15:16:47.184549+00:00 app[worker.1]: Traceback (most recent call last):

2021-06-04T15:16:47.184559+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main

2021-06-04T15:16:47.184560+00:00 app[worker.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)

2021-06-04T15:16:47.184560+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details

2021-06-04T15:16:47.184561+00:00 app[worker.1]:     return _get_module_details(pkg_main_name, error)

2021-06-04T15:16:47.184561+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details

2021-06-04T15:16:47.184562+00:00 app[worker.1]:     __import__(pkg_name)

2021-06-04T15:16:47.184562+00:00 app[worker.1]:   File "/usr/src/app/pmb/__init__.py", line 40, in <module>

2021-06-04T15:16:47.184562+00:00 app[worker.1]:     dynamic.handler()

2021-06-04T15:16:47.184562+00:00 app[worker.1]:   File "/usr/src/app/pmb/helper/config/dynamic.py", line 46, in handler

2021-06-04T15:16:47.184563+00:00 app[worker.1]:     reformatter.handler('config.env')

2021-06-04T15:16:47.184563+00:00 app[worker.1]:   File "/usr/src/app/pmb/helper/config/reformatter.py", line 9, in handler

2021-06-04T15:16:47.184563+00:00 app[worker.1]:     for line in open(fileName, 'r').readlines():

2021-06-04T15:16:47.184564+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: 'config.env'

2021-06-04T15:16:47.246286+00:00 app[worker.1]: Exception ignored in: <function ClientSession.__del__ at 0x7f3c662e69d0>

2021-06-04T15:16:47.246289+00:00 app[worker.1]: Traceback (most recent call last):

2021-06-04T15:16:47.246318+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 337, in __del__

2021-06-04T15:16:47.246318+00:00 app[worker.1]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 1740, in call_exception_handler

2021-06-04T15:16:47.246319+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1463, in error

2021-06-04T15:16:47.246319+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log

2021-06-04T15:16:47.246320+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle

2021-06-04T15:16:47.246320+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers

2021-06-04T15:16:47.246320+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle

2021-06-04T15:16:47.246321+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1182, in emit

2021-06-04T15:16:47.246321+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open

2021-06-04T15:16:47.246322+00:00 app[worker.1]: NameError: name 'open' is not defined

**Comment by priiiiyo** [comment]
At first you not frok my repo... But want help from me 😳
Second You're too noob 😁 READ all instructions 😊

**Comment by amie33r** [comment]
> 
> 
> At first you not frok my repo... But want help from me flushed
> Second You're too noob grin READ all instructions blush
I have made a separate repo, since I've want to keep my credentials a secert, if you still don't understand, see this
https://github.com/amie33r/chg

**Comment by priiiiyo** [comment]
Lol 😂
Then make repo private simple 😊

**Comment by amie33r** [comment]
> 
> 
> Lol joy
> Then make repo private simple blush

Are you going to help? or you gonna just troll?
